### ISSUE TITLE
There should be a warning if you specify two properties that share the same predicate.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#662]
Would help avoid bugs like this:
```
     Failure/Error: let(:object) { TestModel.new(title: ['foo', 'bar'], creator: 'baz') }
     ActiveFedora::ConstraintError:
       Expected "creator" to have 0-1 statements, but there are 2
     # ./spec/presenters/hydra_editor_presenter_spec.rb:23:in `new'
```

Which was caused by title and creator accidentally having the same predicate

**Comment by jcoyne** [comment]
A predicate can be shared if each term has different `class_name` properties. So the warning should only be raised if the cardinality (`multiple` property) is different on both.

**Comment by hectorcorrea** [comment]
@jcoyne A few questions. 

1. Why does the "class_name" matter?

2. Is this the expected behavior for when two properties have the same predicate and 
 
a) if the have the same "class_name" and different "multiple" - OK
b) if the have the same "class_name" and same "multiple" - Warn user
c) if the have the different "class_name" and different "multiple" - OK
d) if the have the different "class_name" and same "multiple" - OK

3. If one (or both) of them have no "class_name" indicated apply the same logic?

**Comment by jcoyne** [comment]
Actually I think the class_name difference only applies to associations (belongs_to, has_many). I may have confused that in my head, so it should probably always warn on duplicate predicates regardless of how any other parameters are set.

**Comment by hectorcorrea** [comment]
@jcoyne I have this note form our IRC chat the other day on which @terrellt brought up "class_name" 

    AT can handle property 

    :title,   :class_name => Title1, :predicate => RDF::DC.title, 
    :title_2, :class_name => Title2, :predicate => RDF::DC.title

    if Title1 and Title2 have defined types which differ.

Is this why you included it perhaps? I've removed the "class_name" check in my PR but I wonder if this changes things.

**Comment by jcoyne** [comment]
Perhaps. It's not a use case I have, see what @terrellt has to say.
