### ISSUE TITLE
Enforce cardinality of properties on ActiveFedora::RDFDatastream like it is for ActiveFedora::Base

### ISSUE THREAD

**Issue by afred** [projecthydra/active_fedora#776]
Here's an example https://gist.github.com/afred/35f8f32e5c4905d5d001.

Not sure if this is by design, but it's confusing to me that they behave differently.

**Comment by awead** [comment]
@afred we added the cardinality enforcement at the Base level because we were working with RDF resources in Fedora 4, as opposed to datastreams in Fedora 3, or non-RDF source in Fedora 4. In previous versions of AF that used ntriples datastreams, I'm not sure it was enforced at all, so it might have just gotten ported over as-is.

We didn't think about adding the enforcement to RDFDatastream classes because if you're using Fedora 4, you shouldn't use them and write your triples to the RDF resource (a.k.a. AF::Base) directly.

**Comment by afred** [comment]
if we shouldn't be using them, then shouldn't we discourage their use with Deprecation warnings? I only see [https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/rdf/rdf_datastream.rb#L25](one in `RDFDatastream`), and it is specific to indexing.

**Comment by jcoyne** [comment]
I'm not sure I agree with @awead that we shouldn't use RDF Datastreams. There are some advantages to writing a self-contained graph (like b-node handling). What's your reasoning @awead?

The reason they behave differently is that `property` in a datastream is a active-triples method. On an ActiveFedora::Base object, it's provided by active-fedora. I wanted to put `multiple: false` in active-triples, but others thought that was not a good idea.

Even though your datastream doesn't have this enforcement, you can add it to your AF::Base object:

```ruby
  property :title, delegate_to: 'descMetadata', multiple: false
```

**Comment by afred** [comment]
@jcoyne do you remember why other thought it wasn't a good idea? Seems reasonable to me.

**Comment by no-reply** [comment]
@afred the proposal under consideration for `ActiveTriples` included silently deleting data.  If the following graph is present in the data store

```
:myResource rdf:type dcmitype:Image
:myResource dc:title "first title" .
:myResource dc:title "second title" .
```

and you have the following model:

```ruby
class Image
  configure type: RDF::DCMITYPE.Image

  property :title, multiple: false 
end
```

and you do `i = Image.new('myResource'); i.title = i.title; i.save`, your new persisted graph will contain one or the other of the titles (depending on the behavior of the datastore, it will be unpredictable which one is retained).

Since `ActiveTriples` is built for access to Linked Data, and there's no concept of single value properties in RDF, it was hard to imagine coming up with a solution that doesn't have similarly problematic behavior in one way or another.

I'm not sure whether Fedora introduces a datastore-level concept of single-valued properties, but if it does not, I'd be interested to see how it behaves if you try to interact with multi-valued data in Fedora on a single-valued AF property.

At least for `ActiveTriples` my sense is still that the best solution is to push enforcement out to validation/forms, etc...

**Comment by afred** [comment]
@no-reply thanks for that explanation. That makes good sense. Now I too, am curious as to how AF would behave if it declares a property as single-valued, but there are multiple values in Fedora.

**Comment by afred** [comment]
So it looks like AF won't delete your data, nor will it arbitrarily choose one of the existing values. But it also doesn't throw any kind of warning.

https://gist.github.com/afred/ef1f7673a7ae64aa4049

**Comment by awead** [comment]
@afred @jcoyne "shouldn't" was a bad choice, and I hadn't thought about the b-node issue. But I imagine most people would want to use RDF properties directly on the resource as opposed to writing Ntriples in text to a non-RDF resource.

**Comment by afred** [comment]
So I think the source of confusion for me is when you call the `property` class method in a `ActiveFedora::RDFDatastream`, then the [`ActiveTriples::Properties.property`](https://github.com/ActiveTriples/ActiveTriples/blob/master/lib/active_triples/properties.rb#L38-L47) method is being executed. But when you call the `property` class method on `ActiveFedora::Base` classes, then [`ActiveFedora::Attributes.property`](https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/attributes.rb#L174-L182) is getting executed.

They look alike, and they are used for the same purpose, but the `ActiveFedora::Properties.property` version is doing extra stuff, in this case, allowing the addition of cardinality constraints.

**Comment by afred** [comment]
^^ If support is continued for `ActiveFedora::RDFDatastream` wouldn't it make more sense to have it implement `ActiveFedora::Attributes.property` instead of `ActiveTriples::Properties.property`, to keep it consistent within the AF family?

**Comment by awead** [comment]
@afred Yes, it would. RDF doesn't really have a notion of singular versus multiple. At least this was how @no-reply explained it. In ActiveTriples, everything can be multiple so in order to enforce cardinality, we put the logic in ActiveFedora. Since RDFDatastream is talking directly to AT, there's no notion of cardinality.

**Comment by afred** [comment]
I'm not savvy enough to know what kind of chaos might ensue if `ActiveFedora::RDFDatastream` implements `ActiveFedora::Attribures.property` instead of `ActiveTriples::Property.property`.

**Comment by jcoyne** [comment]
But then it's not consistent with Om's accessors, which always return a set of things.

**Comment by afred** [comment]
Is the OM pattern worth staying consistent with? Seems like cardinality constraints would make even more sense for OM, since there _is_ a notion of cardinality in xml.

(i thought OM supported something like `multiple: false`)

**Comment by afred** [comment]
Or... should cardinality constraints live in validation logic?

**Comment by jcoyne** [comment]
There is no cardinality in xpath, which is what OM is using under the hood.  Only DTDs (which we aren't using) can validate cardinality.

**Comment by afred** [comment]
So it's more preferable that `RDFDatastream` properties behave like `OmDatastream` "properties", rather than `RDFDatastream` properties behaving like `ActiveFedora::Base` properties?

**Comment by no-reply** [comment]
Should we move this issue to https://github.com/projecthydra-labs/active_fedora-datastreams or simply close?

**Comment by awead** [comment]
I defer to @afred

**Comment by afred** [comment]
I'm fine with closing it.
