### ISSUE TITLE
When query with nil value should always return an empty relation

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#910]
e.g. `Proxy.where(proxyFor_ssim: nil)` instead this is returning all resources that are Proxies

**Comment by ojlyytinen** [comment]
I just ran into a problem which I assume is ultimately caused by this. I got the code below in active_fedora/spec/integration/has_many_associations_spec.rb. Also I changed the before and after blocks which define and remove the classes to run on :each rather than :all. Both of the test cases fail.

The second test case is particularly worrying since this can cause data loss in certain conditions. Basically if you create a new object with a has_many property and leave the property empty, then on saving it will steal all existing parts from all other objects. In this case saving a library with no books will steal all books from all other libraries. 

It seemed that this will only happen in very specific circumstances. I couldn't figure out all the necessary conditions or what exactly causes this but in our case we have presence validation for contributors in Collection and we have also overridden to_solr which does something with contributors. The test case here reflects that and it seems that both validation and referencing books somewhere in the middle of save process is required for this to happen.

```ruby
  context "with presence validation" do
    before do
      Library.class_eval do
        validates :books, presence: true
        def to_solr(solr_doc={})
          books.to_a
          super(solr_doc)
        end
      end
    end

    let( :book1 ) { Book.create }
    let( :book2 ) { Book.create }
    let!( :library1 ) { Library.create(books: [book1, book2]) }

    it "validates presence" do
      library2 = Library.new
      expect(library2).not_to be_valid
    end

    it "doesn't steal all books" do
      library2 = Library.new
      library2.save
      expect(library1.reload.books).not_to be_empty
    end
  end
```
