### ISSUE TITLE
AF config needs a way to inject Faraday options

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/active_fedora#985]
`AF::Fedora#authorized_connection` creates `Faraday.new(host)` which doesn't permit required options for SSL connections.

**Comment by awead** [comment]
I've run into similar problems with SSL and AF.  For example, I wasn't able to used Fedora hosts with self-signed SSL certs because it was looking in the system's location. I had to monkeypatch Faraday:
https://github.com/aic-collections/aicdams-lakeshore/blob/master/config/initializers/faraday.rb
Maybe this might work in your case?

**Comment by jcoyne** [comment]
I suspect this is actually a bug with the ldp gem: https://github.com/projecthydra/ldp

**Comment by dchandekstark** [comment]
@awead I haven't tried with certs, but I had to do this even to bypass verification:

```ruby
module ActiveFedora
  class Fedora
    def authorized_connection
      connection = Faraday.new(host, ssl: { verify: false })
      connection.basic_auth(user, password)
      connection
    end
  end
end
```

**Comment by jcoyne** [comment]
Ignore my last. It is in AF.

**Comment by awead** [comment]
@dchandekstark hmm. Are you just trying to use basic auth to connect to a Fedora instance via https?

**Comment by dchandekstark** [comment]
@awead Yes.

**Comment by awead** [comment]
@dchandekstark I'm able to do this in hydra-jetty:
https://github.com/aic-collections/aicdams-lakeshore/commit/dfc61a1163adbe382d70afd4d6398d48a534a3ea
